fullnameOverride: ""
containerPort: 8080

deployment:
  limits:
    cpu: 200m
    memory: 248Mi
  requests:
    cpu: 100m
    memory: 128Mi

image:
  repository: ""
  tag: latest
  pullPolicy: Always


ingress:
  enabled: true
  ingressClassName: nginx
  tls:
    certManagerIssuer: ""
    secretName: ""
  host: ""
  path:
    pathType: Prefix
    path: "/"