apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.fullnameOverride }}
  annotations:
    cert-manager.io/issuer: {{ .Values.ingress.tls.certManagerIssuer }}
  labels:
    name: {{ .Values.fullnameOverride }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tls.secretName }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: {{ .Values.ingress.path.pathType }}
        path: {{ .Values.ingress.path.path }}
        backend:
          service:
            name: {{ .Values.fullnameOverride }}
            port: 
              number: 80
